### PR TITLE
Fix database link

### PR DESCRIPTION
**Pull request by tekcay**
This PR aims to fix issue #15 by adding Hibernate to the depencendies and using a more recent SQL driver.
The link with the database is set up with the `application.properties` and `persistence.xml` files.
It also provides a README file to setup the database.

### CODE REVIEW

**Review by delhomvi — APPROVED** [review]

**Review by delhomvi — CHANGES_REQUESTED** [review]
Missing target folder

**Comment by tekcay** [comment]
This hopefully should be the last commit, the PR is ready again for review :)

**Review by delhomvi — APPROVED** [review]
changes looks good

**Review by delhomvi — CHANGES_REQUESTED** [review]
move meta inf to ressources

**Review by delhomvi — APPROVED** [review]
Look Good and works

**Pull request merged**
